Import("env")
targets = []

#===================#
#     UNIT TEST     #
#===================#
"""
env1 = env.Clone()
test_unit_test = env1.Program('test-unit-test', ['test-unit-test.cpp'])
run_test_unit_test = env1.UnitTest('test-unit-test.passed', 'test-unit-test')
targets += run_test_unit_test
Alias('test_unit_test', run_test_unit_test)
"""

#====================#
#     TEST UTILS     #
#====================#
test_cloud_viewer = env.mvSLAM_Program('test-cloud-viewer', ['test-cloud-viewer.cpp'])
targets += test_cloud_viewer

test_image_io = env.mvSLAM_Program('test-image-io', ['test-image-io.cpp'])
targets += test_image_io

Return(['targets'])

