Import("env")
targets = []

#=========================#
#     REGULAR TARGETS     #
#=========================#
source_files = ['io.cpp',
                'visual-feature.cpp',
                'sfm.cpp',
               ]    
targets += env.mvSLAM_Library('mvSLAM_vision', source_files)

Return(["targets"])
