Import("env")
targets = []

#====================#
#     TEST UTILS     #
#====================#
test_cloud_viewer = env.mvSLAM_Program('test-cloud-viewer', ['test-cloud-viewer.cpp'])
targets += test_cloud_viewer

test_pcl_visualizer = env.mvSLAM_Program('test-pcl-visualizer', ['test-pcl-visualizer.cpp'])
targets += test_pcl_visualizer 

test_image_io = env.mvSLAM_Program('test-image-io', ['test-image-io.cpp'])
targets += test_image_io

test_visual_feature = env.mvSLAM_Program('test-visual-feature', ['test-visual-feature.cpp'])
targets += test_visual_feature

reconstruct_scene = env.mvSLAM_Program('reconstruct-scene', ['reconstruct-scene.cpp'])
targets += reconstruct_scene

calibrate_camera = env.mvSLAM_Program('calibrate-camera', ['calibrate-camera.cpp'])
targets += calibrate_camera

video_capture = env.mvSLAM_Program('video-capture', ['video-capture.cpp'])
targets += video_capture

Return(['targets'])

