Import("env")

mvSLAM_base_files = [
    './base/math.cpp',
    './base/debug.cpp',
    './base/image.cpp',
    './base/visualization.cpp',
    './base/gtsam.cpp',
]

mvSLAM_os_files = [
    './os/time.cpp',
    './os/event.cpp',
    './os/mutex.cpp',
    './os/directory-iterator.cpp',
]

mvSLAM_vision_files = [
    './vision/camera.cpp',
    './vision/visual-feature.cpp',
    './vision/sfm-solve.cpp',
    './vision/sfm-refine.cpp',
    './vision/pnp-solve.cpp',
    './vision/pnp-refine.cpp',
    './vision/ba.cpp',
    './vision/fundamental-matrix.cpp',
    './vision/estimator-RANSAC.cpp',
]

mvSLAM_back_end_files = [
    './back-end/data-type.cpp',
    './back-end/graph.cpp',
]

mvSLAM_front_end_files = [
    './front-end/data-type.cpp',
    './front-end/frame-manager.cpp',
    './front-end/camera-manager.cpp',
    './front-end/image-pair.cpp',
    './front-end/visual-odometer.cpp',
]

source_files = \
    mvSLAM_base_files + \
    mvSLAM_os_files + \
    mvSLAM_vision_files + \
    mvSLAM_back_end_files + \
    mvSLAM_front_end_files

targets = []
for source_file in source_files:
    object_file = env.Object(source_file)
    targets.append(object_file)

Return(["targets"])
