Import("env")

mvSLAM_base_files = [
    './base/math.cpp',
    './base/image.cpp',
    './base/visualization.cpp',
    './base/gtsam.cpp',
]

mvSLAM_os_files = [
    './os/time.cpp',
    './os/event.cpp',
    './os/mutex.cpp',
    './os/directory-iterator.cpp',
]

mvSLAM_vision_files = [
    './vision/io.cpp',
    './vision/camera.cpp',
    './vision/visual-feature.cpp',
    './vision/sfm-solve.cpp',
    './vision/sfm-refine.cpp',
    './vision/fundamental-matrix.cpp',
    './vision/estimator-RANSAC.cpp',
]

source_files = \
    mvSLAM_base_files + \
    mvSLAM_os_files + \
    mvSLAM_vision_files

targets = []
for source_file in source_files:
    object_file = env.Object(source_file)
    targets.append(object_file)

Return(["targets"])
